#!/bin/bash
##########################################################################
# Copyright 2025 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
##########################################################################
# generate_xs_crl_and_expired_bridge.sh
#
# Post-processing for the cross-signed PKI generated by
# generate_cross_signed_test_certs.sh:
#   1. Generates empty CRLs for all XS CAs (required by OpenSSL 3 CRL_CHECK_ALL)
#   2. Creates a truly-expired bridge cert for the expxs test case
#   3. Re-bundles client-expxs.p12 with the expired bridge
#
# Must be called AFTER generate_cross_signed_test_certs.sh.
#
# Environment variables:
#   XS_CERT_DIR  Root of cross-signed PKI   (default: /etc/pki/test-xs)
#   XS_OUT_DIR   Output directory for CRLs  (default: /etc/xconf/certs/xs)
##########################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/cert_utils.sh"

XS_CERT_DIR="${XS_CERT_DIR:-/etc/pki/test-xs}"
XS_OUT_DIR="${XS_OUT_DIR:-/etc/xconf/certs/xs}"
CERT_PASSWORD="${CERT_PASSWORD:-changeit}"

# Ensure the output directory exists; this script may run standalone (with
# set -euo pipefail a missing dir would abort on the first cp/export).
mkdir -p "${XS_OUT_DIR}"

echo "[xs-post] Post-processing XS PKI: generating CRLs and expired bridge..."

# ── Generate empty CRLs for all XS CAs ───────────────────────────────────────
for _CA_DIR in \
    "${XS_CERT_DIR}/Test-XS-OldRoot" \
    "${XS_CERT_DIR}/Test-XS-OldRoot/Test-XS-OldICA" \
    "${XS_CERT_DIR}/Test-XS-NewRoot"; do
    _CA_NAME=$(basename "${_CA_DIR}")
    _CA_CERT="${_CA_DIR}/certs/${_CA_NAME}.pem"
    _CA_KEY="${_CA_DIR}/private/${_CA_NAME}.key"
    [ -f "${_CA_CERT}" ] && [ -f "${_CA_KEY}" ] || continue

    generate_empty_crl "${_CA_DIR}" "${_CA_NAME}" \
        "${_CA_DIR}/crl/${_CA_NAME}.crl.pem" 365
    cp "${_CA_DIR}/crl/${_CA_NAME}.crl.pem" "${XS_OUT_DIR}/${_CA_NAME}.crl.pem"
done
echo "[xs-post] XS PKI CRLs generated"

# ── Create truly-expired bridge cert ─────────────────────────────────────────
_NEWROOT_CERT="${XS_CERT_DIR}/Test-XS-NewRoot/certs/Test-XS-NewRoot.pem"
_NEWROOT_KEY="${XS_CERT_DIR}/Test-XS-NewRoot/private/Test-XS-NewRoot.key"
_OLDROOT_CERT="${XS_CERT_DIR}/Test-XS-OldRoot/certs/Test-XS-OldRoot.pem"
_OLDROOT_KEY="${XS_CERT_DIR}/Test-XS-OldRoot/private/Test-XS-OldRoot.key"
_EXPXS_BRIDGE="${XS_CERT_DIR}/Test-XS-NewRoot/cross-signed/OldRoot-expxs.pem"
_NR_DIR="${XS_CERT_DIR}/Test-XS-NewRoot"

_OLD_SUBJ=$(openssl x509 -in "${_OLDROOT_CERT}" -noout -subject -nameopt compat 2>/dev/null | sed 's/^subject=//')

# Ensure NewRoot has a CA DB config for signing
create_ca_db_config "${_NR_DIR}" "Test-XS-NewRoot"

# Append v3_ca extensions to the existing config (idempotent — the config may
# already exist and carry the section from a previous run).
if ! grep -q '^\[ v3_ca \]' "${_NR_DIR}/openssl.cnf"; then
    cat >> "${_NR_DIR}/openssl.cnf" << 'EXTEOF'

[ v3_ca ]
basicConstraints       = critical,CA:TRUE
keyUsage               = critical,digitalSignature,cRLSign,keyCertSign
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
EXTEOF
fi

_OLDROOT_EXPIRED_CSR="$(mktemp)"
openssl req -new \
    -key "${_OLDROOT_KEY}" \
    -out "${_OLDROOT_EXPIRED_CSR}" \
    -subj "${_OLD_SUBJ}" 2>/dev/null

openssl ca \
    -config "${_NR_DIR}/openssl.cnf" \
    -in "${_OLDROOT_EXPIRED_CSR}" \
    -out "${_EXPXS_BRIDGE}" \
    -startdate 20240101000000Z \
    -enddate   20240102000000Z \
    -extensions v3_ca \
    -batch \
    -notext 2>/dev/null
rm -f "${_OLDROOT_EXPIRED_CSR}"

# Re-bundle client-expxs.p12 with the expired bridge
_EXPXS_KEY=$(find "${XS_CERT_DIR}" -name "client-expxs.key" 2>/dev/null | head -1)
_EXPXS_PEM=$(find "${XS_CERT_DIR}" -name "client-expxs.pem" 2>/dev/null | head -1)
_OLD_ICA="${XS_CERT_DIR}/Test-XS-OldRoot/Test-XS-OldICA/certs/Test-XS-OldICA.pem"
_CHAIN_TMP="$(mktemp)"
cat "${_OLD_ICA}" "${_OLDROOT_CERT}" "${_EXPXS_BRIDGE}" "${_NEWROOT_CERT}" > "${_CHAIN_TMP}"

PKCS12_PASS="${CERT_PASSWORD}" openssl pkcs12 -export \
    -in "${_EXPXS_PEM}" \
    -inkey "${_EXPXS_KEY}" \
    -certfile "${_CHAIN_TMP}" \
    -out "${XS_OUT_DIR}/client-expxs.p12" \
    -name "client-expxs" \
    -passout env:PKCS12_PASS 2>/dev/null
chmod 600 "${XS_OUT_DIR}/client-expxs.p12"
rm -f "${_CHAIN_TMP}"
echo "[xs-post] Replaced expired bridge with truly-expired cert (2024-01-01/02)"

# Copy NewRoot for trust anchor
[ -f "${_NEWROOT_CERT}" ] && cp "${_NEWROOT_CERT}" "${XS_OUT_DIR}/NewRoot.pem"

echo "[xs-post] Done."
