# Copyright 2025 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
"""
L3 CRL / Cross-signed mTLS test driver

Runs *inside* the native-platform container where:
  - l3testapp (built by run_l2.sh with --enable-l2testing) uses the
    RDK CertSelector API to select a PKCS#12 cert and then performs a
    real libcurl mTLS connection to mock-xconf
  - mockxconf:50061  is the CRL mTLS HTTPS server
  - mockxconf:50062  is the plain-HTTP CRL control endpoint
  - mockxconf:50064  is the OCSP stapling server

For CRL/xsign scenarios (1-4) the Python driver controls server state
(revoke/reset) and then delegates the cert-selector + curl step to l3testapp.
For OCSP stapling scenarios the existing curl subprocess is used to inspect
"SSL certificate status" in the verbose TLS trace.

The tests are skipped when ENABLE_CRL_L3 is not set to "true".
"""

import datetime
import json
import os
import subprocess
import time
import urllib.error
import urllib.request
from collections import namedtuple

import pytest

# ─── Skip guard ──────────────────────────────────────────────────────────────

pytestmark = pytest.mark.skipif(
    os.environ.get("ENABLE_CRL_L3", "false").lower() != "true",
    reason="ENABLE_CRL_L3 is not set to 'true'",
)

# ─── Constants ────────────────────────────────────────────────────────────────

MOCKXCONF_HOST   = os.environ.get("MOCKXCONF_HOST", "mockxconf")
CRL_MTLS_PORT    = 50061
CRL_CONTROL_PORT = 50062
OCSP_STAPLING_PORT = 50064

BASE_URL = f"https://{MOCKXCONF_HOST}:{CRL_MTLS_PORT}"
CTRL_URL = f"http://{MOCKXCONF_HOST}:{CRL_CONTROL_PORT}"
OCSP_URL = f"https://{MOCKXCONF_HOST}:{OCSP_STAPLING_PORT}"

# Client cert assets (on shared volume, generated by mock-xconf)
_SHARED = "/mnt/L2_CONTAINER_SHARED_VOLUME/shared_certs"
CRL_CLIENT_P12    = f"{_SHARED}/crl-client/crl-client.p12"
XS_CLIENT_XSIGN   = f"{_SHARED}/xs-client/client-xsign.p12"
XS_CLIENT_OLD     = f"{_SHARED}/xs-client/client-old.p12"
XS_CLIENT_EXPXS   = f"{_SHARED}/xs-client/client-expxs.p12"

# Path to the client cert *inside mock-xconf container* — used for POST /crl/revoke
# This is the cert recorded in the ICA database (created via openssl ca).
MOCKXCONF_CRL_CLIENT_CERT = (
    "/etc/pki/test-crl/Test-CRL-Root/Test-CRL-ICA/certs/crl-client.pem"
)

CERT_PASS = "changeit"

# Path to the l3testapp binary (built alongside l2sampleapp by run_l2.sh)
L3TESTAPP = "./test/l3-testapp/l3testapp"

# ─── Module-level setup ───────────────────────────────────────────────────────


@pytest.fixture(scope="module", autouse=True)
def _setup_l3_configs():
    """Write certsel config files for l3testapp before any L3 test runs."""
    setup = "./test/l3-testapp/test_setup.sh"
    if os.path.isfile(setup):
        subprocess.run(["sh", setup], check=True)
    else:
        pytest.skip(f"L3 test_setup.sh not found at {setup}")


# ─── Helpers ─────────────────────────────────────────────────────────────────


def run_l3testapp(scenario_id, timeout=10):
    """
    Invoke l3testapp <scenario_id> and return (returncode, stdout, stderr).

    The testapp calls rdkcertselector_getCert to obtain the PKCS#12 cert URI
    and password for the scenario, then makes a real libcurl mTLS connection,
    then calls rdkcertselector_setCurlStatus with the actual CURLcode.

    Exit code 0 means the expected outcome (connected OK for scenarios 1-3,5;
    connection correctly failed for scenarios 3,4,6).
    """
    result = subprocess.run(
        [L3TESTAPP, str(scenario_id)],
        capture_output=True, text=True, timeout=timeout,
    )
    return result.returncode, result.stdout, result.stderr


def curl_mtls(p12_file, url=None, timeout=10):
    """
    Run curl with mTLS for OCSP stapling tests that inspect the verbose trace.
    Returns (returncode, stdout_str, stderr_str).
    """
    if url is None:
        url = f"{BASE_URL}/health"
    cmd = [
        "curl",
        "--silent",
        "--fail-with-body",
        "--cert",      p12_file,
        "--cert-type", "P12",
        "--pass",      CERT_PASS,
        url,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    return result.returncode, result.stdout, result.stderr


# Minimal response wrapper exposing the subset of the requests.Response API
# used by these tests (.status_code and .text).
_CtrlResponse = namedtuple("_CtrlResponse", ["status_code", "text"])


def ctrl_post(endpoint, body=None):
    """POST to the CRL control server using only the Python standard library.

    Returns an object exposing .status_code and .text. Using urllib avoids a
    runtime ``pip install requests`` and keeps the L3 suite free of outbound
    network/package dependencies in egress-restricted CI.
    """
    data = json.dumps(body if body is not None else {}).encode("utf-8")
    req = urllib.request.Request(
        f"{CTRL_URL}{endpoint}",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            return _CtrlResponse(resp.status, resp.read().decode("utf-8", "replace"))
    except urllib.error.HTTPError as exc:
        # An HTTP error response still carries a status code and body.
        return _CtrlResponse(exc.code, exc.read().decode("utf-8", "replace"))


# ─── Test cases ───────────────────────────────────────────────────────────────


def test_l3_crl_valid_cert_succeeds():
    """A valid (non-revoked) client cert must be accepted by the mTLS server."""
    ctrl_post("/crl/reset")
    rc, stdout, stderr = run_l3testapp(1)
    assert rc == 0, (
        f"Expected l3testapp scenario 1 (CRL valid) to succeed (rc={rc}).\n"
        f"stdout: {stdout}\nstderr: {stderr}"
    )


def test_l3_crl_revoked_cert_fails():
    """After revoking a cert the mTLS server must reject it (CRL check)."""
    resp = ctrl_post("/crl/revoke", {"certFile": MOCKXCONF_CRL_CLIENT_CERT})
    assert resp.status_code == 200, (
        f"POST /crl/revoke failed: {resp.status_code} {resp.text}"
    )
    # Brief pause to let setSecureContext() propagate the new CRL to the server
    time.sleep(0.3)

    rc, _, stderr = run_l3testapp(1)
    assert rc != 0, (
        "Expected l3testapp scenario 1 to fail after revocation but it succeeded.\n"
        f"stderr: {stderr}"
    )


def test_l3_crl_reset_restores():
    """After a CRL reset a previously revoked cert should be accepted again."""
    # Ensure clean state (prior test may have left cert revoked)
    ctrl_post("/crl/reset")

    # Revoke first
    resp = ctrl_post("/crl/revoke", {"certFile": MOCKXCONF_CRL_CLIENT_CERT})
    assert resp.status_code == 200
    time.sleep(0.3)

    # Confirm cert is rejected while revoked
    rc_revoked, _, _ = run_l3testapp(1)
    assert rc_revoked != 0, "Cert should be rejected while revoked"

    # Reset CRL
    resp = ctrl_post("/crl/reset")
    assert resp.status_code == 200, (
        f"POST /crl/reset failed: {resp.status_code} {resp.text}"
    )

    # Now cert should be accepted again
    rc, _, stderr = run_l3testapp(1)
    assert rc == 0, (
        f"Expected cert to be accepted after CRL reset (rc={rc}).\n"
        f"stderr: {stderr}"
    )


def test_l3_xsign_bridge_succeeds():
    """
    A client cert whose chain includes a valid cross-signed bridge must be
    accepted.  The server trusts Test-XS-NewRoot; the bridge cert links
    Test-XS-OldRoot to Test-XS-NewRoot.
    """
    rc, stdout, stderr = run_l3testapp(2)
    assert rc == 0, (
        f"Expected l3testapp scenario 2 (xsign bridge) to succeed (rc={rc}).\n"
        f"stdout: {stdout}\nstderr: {stderr}"
    )


def test_l3_xsign_no_bridge_fails():
    """
    A client cert under Test-XS-OldRoot with no bridge must be rejected: the
    server does not directly trust Test-XS-OldRoot.
    """
    rc, _, stderr = run_l3testapp(3)
    assert rc != 0, (
        "Expected l3testapp scenario 3 (xsign no bridge) to fail, but it succeeded.\n"
        f"stderr: {stderr}"
    )


def test_l3_xsign_expired_bridge_fails():
    """
    A client cert whose chain includes an already-expired bridge cert must be
    rejected.  The test must also complete in under 5 seconds (no TLS retry
    hang).
    """
    start = datetime.datetime.now()
    rc, _, stderr = run_l3testapp(4, timeout=10)
    elapsed = (datetime.datetime.now() - start).total_seconds()

    assert rc != 0, (
        "Expected l3testapp scenario 4 (expired bridge) to fail, but it succeeded.\n"
        f"stderr: {stderr}"
    )
    assert elapsed < 5.0, (
        f"Test took {elapsed:.1f}s — expected under 5s (possible TLS hang on "
        "expired bridge cert)."
    )


# ─── OCSP Stapling tests ───────────────────────────────────────────────────────


def test_l3_ocsp_staple_present():
    """
    OCSP Stapling – happy path.

    curl --cert-status requests a TLS status_request (RFC 6066).  The server
    on port 50064 must staple a valid OCSP response into the handshake.
    The -vv trace must contain "SSL certificate status: good".

    Architecture owner spec:
      "Attempt a curl connection with --cert-status & -vv option from
       native-platform to server instance.  Verify the connection trace that
       the server responds to OCSP request."
    """
    cmd = [
        "curl",
        "--cert-status",          # request OCSP stapling; fail if not present
        "-vv",                    # verbose — staple status appears in stderr
        "--silent",
        "--fail-with-body",
        f"{OCSP_URL}/health",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)

    assert result.returncode == 0, (
        f"curl --cert-status failed (rc={result.returncode}).\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}\n"
        "Server must staple a valid OCSP response when ENABLE_CRL_L3=true."
    )
    # curl prints "SSL certificate status: good" in verbose output when the
    # server staples a valid OCSP response with status=good.
    assert "SSL certificate status: good" in result.stderr, (
        "Expected 'SSL certificate status: good' in curl -vv output.\n"
        f"stderr: {result.stderr}"
    )


def test_l3_ocsp_staple_absent_rejected():
    """
    OCSP Stapling – curl --cert-status must fail when connecting to a server
    that does NOT staple.

    This is a negative control: the CRL mTLS server on port 50061 does not
    implement OCSP stapling.  curl --cert-status must fail because the server
    provides no OCSP response, proving that the test_l3_ocsp_staple_present
    assertion is meaningful and not a false positive.
    """
    cmd = [
        "curl",
        "--cert-status",          # will fail if no OCSP staple is returned
        "--silent",
        "--fail-with-body",
        "--cert",      CRL_CLIENT_P12,
        "--cert-type", "P12",
        "--pass",      CERT_PASS,
        f"{BASE_URL}/health",     # port 50061 — no OCSP stapling
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)

    assert result.returncode != 0, (
        "Expected curl --cert-status to fail against a non-stapling server, "
        f"but it succeeded.\nstderr: {result.stderr}"
    )
