# Copyright 2024 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

# build with
CC           = gcc
#
CFLAGS       = -I ../include
CFLAGS       += -Wall -Wno-unused-function -Os -std=gnu99
CFLAGS       += -Wfatal-errors
CFLAGS       += -Werror

MAKEFILE         = Makefile.vm

.SILENT:
.PHONY:  clean ut ct

all: utrdkconfig

SRCS += rdkconfig.c rdkconfig.h

OBJS = $(filter %.o,$(SRCS:.c=.o))


utrdkconfig : rdkconfig.c  $(MAKEFILE)
	@echo "building utrdkconfig"
	$(CC) $(CFLAGS) -DUNIT_TESTS rdkconfig.c -o $@

utgscf : GetSaveConfigFile.c $(MAKEFILE)
	@echo "building utgscf"
	$(CC) $(CFLAGS) -DUNIT_TESTS GetSaveConfigFile.c -o $@

./ut/tmp/ :
	mkdir -p ./ut/tmp/

ut : utrdkconfig utgscf ./ut/tmp/
	./utrdkconfig
	./utgscf

librdkconfig.a : rdkconfig.c
	@echo "building librdkconfig.a"
	ar -rcs librdkconfig.a rdkconfig.o

GetSaveConfigFile : GetSaveConfigFile.c librdkconfig.a
	@echo "building GetSaveConfigFile"
	$(CC) $(CFLAGS) GetSaveConfigFile.c -o $@ -L. -lrdkconfig

GetConfigFile : GetSaveConfigFile
	ln -s GetSaveConfigFile GetConfigFile

SaveConfigFile : GetSaveConfigFile
	ln -s GetSaveConfigFile SaveConfigFile


tsts : ut

clean :
	rm -f *.o *.so *.map utrdkconfig utgscf utst*	
	rm -f librdkconfig.a GetSaveConfigFile
	rm -rf ./ut/
