#!/bin/bash

# ============================================================================
# PKCS#11 mTLS Integration Test - rdkfwupdater with Reference P12 Patch
# ============================================================================
# Tests the complete PKCS#11 reference P12 workflow for rdkfwupdater:
# 1. Verify reference.p12 was created by container with sentinel key
# 2. Verify real private key exists in PKCS#11 token (ID 0x2c)
# 3. Test mTLS connections using reference.p12 to rdkfwupdater endpoints
#
# Expected Behavior:
# - reference.p12 contains certificate + sentinel key (zeroed private value)
# - OpenSSL PKCS#11 patch detects sentinel key pattern
# - OpenSSL redirects to PKCS#11 token to load real private key (ID 0x2c)
# - mTLS handshakes complete successfully with real key from PKCS#11
#
# This validates the production workflow: P12 file → PKCS#11 HSM
# ============================================================================

set -e

# Load PKCS#11 configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/pkcs11_config.sh"

echo "════════════════════════════════════════════════════════════"
echo "PKCS#11 mTLS Integration Test - rdkfwupdater"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Testing rdkfwupdater with Reference P12 + PKCS#11 Patch"
echo "Certificate: rdkclient-p12 (ID: 0x2c)"
echo "Token: $PKCS11_TOKEN_LABEL"
echo ""

# ============================================================================
# STEP 1: Verify reference.p12 exists
# ============================================================================
echo "Step 1: Verify reference P12 exists (generated by container)"

if [ ! -f "$REFERENCE_P12" ]; then
    echo "✗ FAIL: reference.p12 not found at $REFERENCE_P12"
    echo ""
    echo "Troubleshooting:"
    echo "  • Verify ENABLE_PKCS11=true was set when starting container"
    echo "  • Check container logs: docker logs native-platform | grep 'PKCS#11'"
    echo "  • Verify certs.sh script ran: docker logs native-platform | grep 'certs'"
    exit 1
fi

echo "✓ Container-generated reference.p12 found"
echo "  Location: $REFERENCE_P12"
echo "  Size: $(stat -c%s "$REFERENCE_P12") bytes"
echo ""

# ============================================================================
# STEP 2: Verify real private key in PKCS#11 token
# ============================================================================
echo "Step 2: Verify real private key exists in PKCS#11 token (slot 0x2c)"

# List objects in PKCS#11 token and check for ID 2c
PKCS11_OBJECTS=$(pkcs11-tool --module "$PKCS11_MODULE_PATH" \
    --token-label "$PKCS11_TOKEN_LABEL" --pin "$PKCS11_TOKEN_PIN" \
    -O 2>&1)

if echo "$PKCS11_OBJECTS" | grep -q "ID: 2c"; then
    echo "✓ Real private key with ID 2c found in PKCS#11 token"
    
    # Show certificate details
    if echo "$PKCS11_OBJECTS" | grep -A5 "ID: 2c" | grep -q "label:.*rdkclient-p12"; then
        echo "  Label: rdkclient-p12"
    fi
else
    echo "✗ FAIL: Real private key not found in PKCS#11 token"
    echo ""
    echo "Troubleshooting:"
    echo "  • List all objects: pkcs11-tool --module $PKCS11_MODULE_PATH -O"
    echo "  • Check token initialization: softhsm2-util --show-slots"
    echo "  • Verify pkcs11_import.sh ran during container startup"
    exit 1
fi
echo ""

# ============================================================================
# STEP 3: Test mTLS connections with reference.p12
# ============================================================================
echo "Step 3: Test mTLS connections using reference P12 to all rdkfwupdater endpoints"
echo ""

# Test endpoints array: URL|Description
ENDPOINTS=(
    "$XCONF_FIRMWARE_URL|XConf Firmware Update"
    "$DCM_SETTINGS_URL|T2 DCM Settings"
    "$DATALAKE_URL|Data Lake"
)

PASSED=0
TOTAL=0

for endpoint in "${ENDPOINTS[@]}"; do
    IFS='|' read -r URL DESCRIPTION <<< "$endpoint"
    TOTAL=$((TOTAL + 1))
    
    echo "  Testing: $DESCRIPTION"
    
    # Use curl with reference.p12
    # The PKCS#11 patch in OpenSSL will:
    # 1. Open reference.p12
    # 2. Detect sentinel key (zeroed private value)
    # 3. Redirect to PKCS#11 token to load real private key (ID 0x2c)
    # 4. Complete mTLS handshake with real key
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
        --cert-type P12 --cert "${REFERENCE_P12}:${P12_PASSWORD}" \
        --cacert "$CA_CERT" \
        --connect-timeout 10 \
        "$URL" 2>&1)
    
    # Accept 200 (success) or 404 (mTLS successful, endpoint not configured)
    if [[ "$HTTP_CODE" == "200" ]]; then
        echo "  ✓ HTTP 200 (endpoint active)"
        PASSED=$((PASSED + 1))
    elif [[ "$HTTP_CODE" == "404" ]]; then
        echo "  ⚠ HTTP 404 (mTLS successful, endpoint not configured)"
        PASSED=$((PASSED + 1))
    else
        echo "  ✗ HTTP $HTTP_CODE (Expected 200 or 404)"
    fi
done

echo ""
echo "  Results: $PASSED/$TOTAL endpoints passed"

if [ $PASSED -eq $TOTAL ]; then
    echo "✓ All mTLS connections successful"
else
    echo "✗ Some mTLS connections failed"
fi
echo ""

# ============================================================================
# Summary and Results
# ============================================================================
echo "════════════════════════════════════════════════════════════"
echo "PKCS#11 mTLS Test Results - rdkfwupdater"
echo "════════════════════════════════════════════════════════════"
echo "  Reference P12 verification:  ✓ PASSED"
echo "  PKCS#11 token verification:  ✓ PASSED"
echo "  Reference P12 mTLS tests:    $PASSED/$TOTAL endpoints passed"
echo ""

if [ $PASSED -eq $TOTAL ]; then
    echo "✓ PKCS#11 mTLS Integration Test PASSED"
    echo ""
    echo "Summary:"
    echo "  • Sentinel key (zeroed private value) successfully created"
    echo "  • OpenSSL patch detected reference key pattern"
    echo "  • Real private key loaded from PKCS#11 slot 0x2c"
    echo "  • mTLS handshakes completed successfully"
    echo ""
    echo "What This Validates:"
    echo "  • rdkfwupdater can use reference.p12 for mTLS"
    echo "  • OpenSSL PKCS#11 patch correctly intercepts sentinel key"
    echo "  • Private key operations are performed by PKCS#11 HSM"
    echo "  • Production workflow (P12 file → PKCS#11 HSM) is working"
    exit 0
else
    echo "✗ PKCS#11 mTLS Integration Test FAILED"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Verify OpenSSL version: $OPENSSL_BIN version"
    echo "     Expected: OpenSSL 3.0.5"
    echo ""
    echo "  2. Check PKCS#11 patch is applied:"
    echo "     $OPENSSL_BIN engine -t pkcs11"
    echo ""
    echo "  3. Inspect reference.p12 structure:"
    echo "     $OPENSSL_BIN pkcs12 -in $REFERENCE_P12 -passin pass:$P12_PASSWORD -info -noout"
    echo ""
    echo "  4. Manually test P12:"
    echo "     curl -vvv --cert-type P12 --cert $REFERENCE_P12:$P12_PASSWORD \\"
    echo "       --cacert $CA_CERT \\"
    echo "       https://mockxconf:50052/firmwareupdate/getfirmwaredata"
    echo ""
    echo "  5. Check PKCS#11 token objects:"
    echo "     pkcs11-tool --module $PKCS11_MODULE_PATH -O"
    exit 1
fi
